((ionic) ->
  # SCREENWIDTH = screen.width;
  # CARDWIDTH = 120;
  angular.module('ionic.contrib.ui.hscrollcards', [ 'ionic' ]).directive('hscroller', [
    '$timeout'
    ($timeout) ->
      {
        restrict: 'E'
        template: '<div class="hscroller" ng-transclude></div>'
        replace: true
        transclude: true
        compile: (element, attr) ->
          ($scope, $element, $attr) ->
            el = $element[0]
            angular.element($element).bind 'scroll', ->
              left = $element[0].scrollLeft

      }
  ]).directive 'hcard', [
    '$rootScope'
    ($rootScope) ->
      {
        restrict: 'E'
        template: '<div class="hscroller-card" ng-transclude></div>'
        replace: true
        transclude: true
        scope:
          desc: '@'
        link: (scope, element, attrs) ->
          name = angular.element("<span>#{attrs.desc}</span>")
          element.append name

      }
  ]
  return
) window.ionic

# ---
# generated by js2coffee 2.2.0